#!/bin/bash
# Copyright (c) 2009-2011 VMware, Inc.
# Try to detect platform. VCAP installs well on Ubuntu and MacOS X Systems.

usage() {
cat <<EOF
usage: $0 options

OPTIONS:
  -h           Show this message
  -a           Answer yes to all questions
  -s           Install all optional services
  -p PASSWORD  Preseed the MySQL password
  -q PASSWORD  Preseed the PostgreSQL password
EOF
}

while getopts "hasp:q:" OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
    a)
      ALL=true
      ;;
    s)
      ALL_SERVICES=true
      ;;
    p)
      MYSQL_PASS="$OPTARG"
      ;;
    q)
      POSTGRESQL_PASS="$OPTARG"
      ;;
  esac
done

RHEL=`uname -r | pcregrep -ce'el5$'`
ARCH=`uname -m`
if [[ $RHEL != 1 ]]; then
    echo "Not RHEL (or CentOS) 5, cancelling set-up"
    exit 1
else
    PLATFORM='RHEL/CentOS 5'
fi

echo ""
echo '-----------------------------------------------------------'
echo "($PLATFORM) Setup for VMware's Cloud Application Platform!"
echo '-----------------------------------------------------------'
echo ""


if [[ $ALL != true ]]; then
  echo "Just hit <enter> to skip any item"
  echo ""
fi

if [ "$(id -u)" != "0" ]; then
    echo '** Setup must be run as root **'
    exit 1
fi

if [[ $ALL != true ]]; then
  read -p "Setup all components? default: individual components? [y/N]"
  if [[ $REPLY =~ ^[yY]$ ]]; then
      ALL=true
  fi
fi

echo "Installing default packages"
yum -qy install wget curl bison zlib openssl-devel.$ARCH readline-devel.$ARCH libxml2 libxml2-devel.$ARCH libxslt libxslt-devel.$ARCH sqlite ruby-sqlite3 sqlite-devel.$ARCH unzip zip

# This is site/setup specific, can be commented out if not needed.
# export http_proxy='http://192.168.208.20:3128'

echo "Creating default directories at /var/vcap"

if [ ! -d '/var/vcap' ]; then
    mkdir /var/vcap
    mkdir /var/vcap/sys
    mkdir /var/vcap/sys/log
    mkdir /var/vcap/shared
    mkdir /var/vcap/services
    chmod -R 777 /var/vcap
fi

if [[ ! "$(bundle -v)" =~ "1.0.10" ]]; then
    echo "Installing bundler 1.0.10"
    gem install bundler -v 1.0.10 --no-rdoc --no-ri
fi

#######################################################################

# Router
if [[ $ALL != true ]]; then
    echo ""
    read -p "Should I do a Router setup? [y/N] "
    if [[ $REPLY =~ ^[yY]$ ]]; then
        ROUTER=true
    fi
fi

if [[ $ROUTER == true || $ALL == true ]]; then

    echo "Installing Nginx."
	yum -qy install nginx
    echo ""
fi

# CloudController
if [[ $ALL != true ]]; then
    read -p "Should I do a CloudController setup? [y/N] "
    if [[ $REPLY =~ ^[yY]$ ]]; then
        CC=true
    fi
fi

if [[ $CC == true || $ALL == true ]]; then
        if [[ $ALL != true ]]; then
            read -p "Should I do a production setup as well (Postgres/MySQL)? [y/N] "
            if [[ $REPLY =~ ^[yY]$ ]]; then
                RELATIONAL_DBS=true
            fi
        fi

	if [[ $RELATIONAL_DBS == true || $ALL == true ]]; then
	    echo "Installing PostgreSQL server and support"
	    yum -qy install postgresql84 postgresql84-server postgresql84-devel.$ARCH
	    if [[ -n "$POSTGRESQL_PASS" ]]; then
		su - postgres -c "/usr/bin/psql -c \"alter role postgres password '$POSTGRESQL_PASS'\""
	    fi
	    echo "Installing pg gems"
	    gem install pg --no-rdoc --no-ri
	    echo ""
	    echo "Installing MySQL server and support"
          yum -qy install mysql mysql-server mysql-devel.$ARCH
          service mysqld start
          mysqladmin --user=root password $MYSQL_PASS
          service mysqld stop
	    echo "Installing mysql gems"
	    gem install mysql --no-rdoc --no-ri
	    echo ""
	fi
    # note: vcap start runs db:migrate on each cloud boot
    # no need to run anything during setup
fi

# DEA
if [[ $ALL != true ]]; then
    read -p "Should I do a DEA setup (Java, Ruby, Node, etc)? [y/N] "
    if [[ $REPLY =~ ^[yY]$ ]]; then
        DEA=true
    fi
fi

if [[ $DEA == true || $ALL == true ]]; then
    echo "Setting up for support for DEA"

    # lsof support for secure dea monitoring, psmisc is for JeOS, which has killall5, not killall
	yum -qy install lsof psmisc

    # For Ruby
	yum -qy install ruby-RMagick

    # Java
	JAVA=`java -version 2>&1 | pcregrep -oe "[\d\.]{5}_\d+"`

    if [[ $JAVA == '' ]]; then
        echo "Installing Sun Java 1.6"
        yum -qy install java-1.6.0-openjdk 
    fi

    # Node and Erlang frameworks
    pushd .
    cd /tmp

    NODE_VERSION=0.4.7

    if [[ ! `node -v` == 'v'$NODE_VERSION ]]; then
	wget http://nodejs.org/dist/node-v$NODE_VERSION.tar.gz
	tar -zxf node-v$NODE_VERSION.tar.gz
	cd node-v$NODE_VERSION
	./configure
	make
	make install
	cd ..
	rm node-v$NODE_VERSION.tar.gz
	rm -fr node-v$NODE_VERSION
    fi

    ERLANG_VERSION=R14B02

    if [ ! -d "/var/vcap/runtimes/erlang$ERLANG_VERSION" ]; then
        yum -qy install ncurses openssl openssl-devel.$ARCH

        wget http://erlang.org/download/otp_src_$ERLANG_VERSION.tar.gz
        tar zxvf otp_src_$ERLANG_VERSION.tar.gz
        cd otp_src_$ERLANG_VERSION

        ./configure --prefix /var/vcap/runtimes/erlang-$ERLANG_VERSION
        make
        make install
    fi
    popd

    echo "App Platform Support"
    echo "===================="

    echo -e "\nRuby should now be installed -->"
    ruby -v

    echo -e "\nJava should now be installed -->"
    java -version

    echo -e "\nNode should now be installed -->"
    node -v
    echo ""

    echo -e "\nErlang should now be installed -->"
    erl -version
    echo ""

    echo "Setting up Ruby System Gems and Support"
	yum -qy install ruby-devel ruby-mysql mysql-devel.$ARCH ruby-postgres postgres 

    echo "Installing some default system gems"
    echo "gem: --no-rdoc --no-ri" > ~/.gemrc

    # original code did this in one shot, BUT with the rake issues with 0.9.0 and rails 3
    # we hard version the rake gem to 0.8.7 since that is the only one that really works
    gem install rack
    gem install rake --version '0.8.7'
    gem install thin sinatra eventmachine

    if [ ! -d '/var/vcap.local' ]; then
	echo "Creating directory /var/vcap.local"
	mkdir "/var/vcap.local"
	chmod  777 "/var/vcap.local"
    fi

if [[ $ALL != true ]]; then
    read -p "Should I do a production setup and secure this system? [y/N] "
    if [[ $REPLY =~ ^[yY]$ ]]; then
        PROD_SETUP=true
        # Setup var directory
        echo "Securing directories and permissions"
        chmod 755 "/var"
        chmod -R 700 "/var/vcap/sys"
        chmod -R 700 "/var/vcap/shared"
        chmod -R 700 "/var/vcap.local"
        chmod -R 711 "/var/vcap.local"
        chmod -R 711 "/var/vcap.local/apps"
        chmod -R 700 "/tmp"
        chmod -R 700 "/var/tmp"
    fi
fi

###################

echo ""
echo "Additional Optional Services"

# if you answered no to the production setup
# question than you should answer yes here for sure
X=`which mysqld`
if [ $? != 0 ]; then
    if [[ $ALL_SERVICES != true ]]; then
        read -p "Should I add MySQL Server? [y/N] "
        if [[ $REPLY =~ ^[yY]$ ]]; then
            MYSQL=true
        fi
    fi

    if [[ $MYSQL == true || $ALL_SERVICES == true ]]; then
        echo "Installing MySQL server and support"
          yum -qy install mysql mysql-server mysql-devel.$ARCH
          service mysqld start
          mysqladmin --user=root password $MYSQL_PASS
          service mysqld stop

	    echo "Installing mysql gems"
	    gem install mysql --no-rdoc --no-ri
	    echo ""
    fi
fi

REDIS_VERSION=2.2.4

redis_current=`redis-server -v | grep $REDIS_VERSION`

if [[ $ALL_SERVICES != true ]]; then
    read -p "Should I add Redis Server? [y/N] "
    if [[ $REPLY =~ ^[yY]$ ]]; then
        REDIS=true
    fi
fi

if [[ $REDIS == true || $ALL_SERVICES == true ]]; then
	echo "Installing Redis (version $REDIS_VERSION)"
	pushd .
	cd /tmp
	wget --no-check-certificate -O redis_master.tgz http://redis.googlecode.com/files/redis-$REDIS_VERSION.tar.gz
	tar -zxf redis_master.tgz
	cd redis-$REDIS_VERSION/src
	make
	cp redis-server /usr/bin
	cp redis-cli /usr/bin
	cd ../..
	rm redis_master.tgz
	rm -fr redis-$REDIS_VERSION
	popd
    fi
else
    echo "Redis Server (version 2.2.2) is current"
fi

RABBITMQ_VERSION=2.4.0
RABBITMQ_VERSION_FULL=2.4.0-1

if [[ $ALL_SERVICES != true ]]; then
    read -p "Should I add RabbitMQ Server? [y/N] "
    if [[ $REPLY =~ ^[yY]$ ]]; then
        RABBITMQ=true
    fi
fi

if [[ $RABBITMQ == true || $ALL_SERVICES == true ]]; then
    echo "Installing RabbitMQ Server (version $RABBITMQ_VERSION)"
    yum -qy install erlang
    pushd .
    cd /tmp
    wget http://www.rabbitmq.com/releases/rabbitmq-server/v$RABBITMQ_VERSION/rabbitmq-server-$RABBITMQ_VERSION_FULL.noarch.rpm
    yum -qy localinstall rabbitmq-server_$RABBITMQ_VERSION_FULL.noarch.rpm
    rm rabbitmq-server_$RABBITMQ_VERSION_FULL.noarch.rpm
    popd
fi

MONGODB_VERSION=1.8.1

mongodb_current=`mongod --version | grep $MONGODB_VERSION`

if [[ -z "$mongodb_current" ]]; then
    if [[ $ALL_SERVICES != true ]]; then
        read -p "Should I add the MongoDB Server? [y/N] "
        if [[ $REPLY =~ ^[yY]$ ]]; then
            MONGODB=true
        fi
    fi

    if [[ $MONGODB == true || $ALL_SERVICES == true ]]; then
	echo "Installing MongoDB Server (version $MONGODB_VERSION)"
	if [[ $ARCH =~ "x86_64" ]] ; then
	    mongodb="mongodb-linux-x86_64-$MONGODB_VERSION"
	    echo "Installing 64-bit version"
	else
	    mongodb="mongodb-linux-i686-$MONGODB_VERSION"
	    echo "Installing 32-bit version"
	fi

	pushd .
	cd /tmp
	wget http://fastdl.mongodb.org/linux/$mongodb.tgz
	tar -zxvf $mongodb.tgz
	cp $mongodb/bin/* /usr/bin
	rm $mongodb.tgz
	rm -fr $mongodb
	popd
    fi
else
    echo "MongoDB Server (version $MONGODB_VERSION) is current"
fi

echo -e "\n\nYou should be good to go!!\n\n"
ruby -v

echo -n "Gem version: "
gem -v

echo -e "\nGem List"
gem list --local

echo -e "\n\nBYE!\n\n"


